#애플리케이션 포트 설정
server:
  port: 9095

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://222.119.100.81:3382/mobul?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: mobul
    password: mobul123
  thymeleaf:
    cache: false


  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true



  # livereload 자동
  devtools:
    livereload:
      enabled=true:


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace




























# properties 용 설정


#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db_codingrecipe?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: mobul
#    password: mobul123
#  thymeleaf:
#    cache: false
#
#
#  # spring data jpa 설정
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#
#
#
#
#  #MySQL 연결설정
#  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#  spring.datasource.url=jdbc:mysql://222.119.100.81:3382/mobul?serverTimezone-UTC
#  spring.datasource.username=mobul
#  spring.datasource.password=mobul123
#