drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,   -- java long == h2 bigint   // db가 자동으로 id 값을 채워 준다
    name varchar(255),
    primary key (id)
);